### ISSUE TITLE
Missing releases/tags

### ISSUE THREAD

**Issue by mlocati** [guyasyou/Pure-Cookies-Notice#3]
We can install this package using composer, by adding to `composer.json` this line:

```json
"require": {
    "guyasyou/pure_cookies_notice": "dev-master"
}
```

BTW, it would be very handy to be able to work with versions (using `dev-master` requires a value of `dev` for `minimum-stability` in `composer.json`).

So, what about adding version (in packagist terms)?

It's as simple as:
1. go to https://github.com/guyasyou/Pure-Cookies-Notice/releases/new
1. in the tag version: enter the package version (`1.3.2`)
1. in the release title: enter the package version

After a couple of minutes, packagist should automatically recognize the `1.3.2` version, and it will be displayed at https://packagist.org/packages/guyasyou/pure_cookies_notice

**Comment by guyasyou** [comment]
I was do it. 
Is it correct?

**Comment by mlocati** [comment]
Perfect, thanks! See https://packagist.org/packages/guyasyou/pure_cookies_notice
